<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        $records = [
            ["id" => 1, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Programa", "es": "Programa"}', "route" => "/program/data" ,"pmenus_id" => 2, "order" => 1, "deep" => 2, "type" => "route", "icon" => "", "level" => 5, "group" => null, "group_description" => null, ],
            ["id" => 2, "created_at" => now(), "updated_at" => now(), "description" => '{"en":"Councilors","es":"Concejales"}', "route" => "" ,"pmenus_id" => 2, "order" => 1, "deep" => 1, "type" => "route", "icon" => "la la-briefcase", "level" => 5, "group" => null, "group_description" => null, ],
            ["id" => 3, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Cementery", "es": "Cementerio"}', "route" => "" ,"pmenus_id" => 3, "order" => 2, "deep" => 1, "type" => "route", "icon" => "la la-taxi", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 4, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Altas", "es": "Altas"}', "route" => "/cementery/death" ,"pmenus_id" => 10, "order" => 2, "deep" => 2, "type" => "route", "icon" => "la la-taxi", "level" => 2, "group" => "cementery", "group_description" => '{"en": "Cementery", "es": "Cementerio"}', ],
            ["id" => 5, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión", "es": "Gestión"}', "route" => "/cementery/deaths" ,"pmenus_id" => 10, "order" => 2, "deep" => 2, "type" => "route", "icon" => "la la-taxi", "level" => 2, "group" => "cementery", "group_description" => '{"en": "Cementery", "es": "Cementerio"}', ],
            ["id" => 6, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Sports", "es": "Deporte"}', "route" => "" ,"pmenus_id" => 6, "order" => 3, "deep" => 1, "type" => "route", "icon" => "la la-bicycle", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 8, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Buscar inscripción", "es": "Buscar inscripción"}', "route" => "/sports/registrations" ,"pmenus_id" => 6, "order" => 3, "deep" => 2, "type" => "route", "icon" => "la la-file-alt", "level" => 2, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 10, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Servicios", "es": "Servicios"}', "route" => "" ,"pmenus_id" => 10, "order" => 4, "deep" => 1, "type" => "route", "icon" => "la la-university", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 11, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Registrar incidencia", "es": "Registrar incidencia"}', "route" => "/services/event" ,"pmenus_id" => 10, "order" => 4, "deep" => 2, "type" => "route", "icon" => "la la-exclamation-triangle", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 12, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Incidencias", "es": "Incidencias"}', "route" => "/services/events" ,"pmenus_id" => 10, "order" => 4, "deep" => 2, "type" => "route", "icon" => "las la-clipboard", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 13, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Inscripciones", "es": "Inscripciones"}', "route" => "/sports/registrations" ,"pmenus_id" => 6, "order" => 2, "deep" => 2, "type" => "route", "icon" => "la la-file-alt", "level" => 2, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 14, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Admin", "es": "Admin"}', "route" => "" ,"pmenus_id" => 14, "order" => 5, "deep" => 1, "type" => "route", "icon" => "la la-cog", "level" => 10, "group" => null, "group_description" => null, ],
            ["id" => 15, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión grupos", "es": "Gestión grupos"}', "route" => "/admin/groups" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-users", "level" => 10, "group" => null, "group_description" => null, ],
            ["id" => 16, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Users management", "es": "Gestión usuarios"}', "route" => "/admin/users" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-user", "level" => 10, "group" => null, "group_description" => null, ],
            ["id" => 18, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Contacts management", "es": "Gestión contactos"}', "route" => "/general/contacts" ,"pmenus_id" => 24, "order" => 8, "deep" => 2, "type" => "route", "icon" => "las la-address-book", "level" => 2, "group" => "general", "group_description" => '{"en": "General", "es": "General"}', ],
            ["id" => 19, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Personal", "es": "Personal"}', "route" => "" ,"pmenus_id" => 19, "order" => 6, "deep" => 1, "type" => "route", "icon" => "la la-users", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 20, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión empleados", "es": "Gestión empleados"}', "route" => "/staff/employees" ,"pmenus_id" => 19, "order" => 6, "deep" => 2, "type" => "route", "icon" => "", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 21, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Ver vacaciones/bajas", "es": "Ver vacaciones/bajas"}', "route" => "/staff/employees/holidays" ,"pmenus_id" => 19, "order" => 6, "deep" => 2, "type" => "route", "icon" => "la la-calendar", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 22, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Social Services", "es": "Servicios Sociales"}', "route" => "" ,"pmenus_id" => 22, "order" => 7, "deep" => 1, "type" => "route", "icon" => "las la-universal-access", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 23, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión expedientes", "es": "Gestión expedientes"}', "route" => "/social-services/files" ,"pmenus_id" => 22, "order" => 7, "deep" => 2, "type" => "route", "icon" => "", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 24, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "General", "es": "General"}', "route" => "" ,"pmenus_id" => 24, "order" => 8, "deep" => 1, "type" => "route", "icon" => "la la-globe", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 25, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Recaudación", "es": "Recaudación"}', "route" => "" ,"pmenus_id" => 25, "order" => 9, "deep" => 1, "type" => "route", "icon" => "la la-money", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 26, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Added values admin", "es": "Gestión plusvalías"}', "route" => "/treasury/va-liquidations" ,"pmenus_id" => 25, "order" => 2, "deep" => 2, "type" => "route", "icon" => "la la-edit", "level" => 2, "group" => "va-liquidation", "group_description" => '{"en": "Value added", "es": "Plusvalias"}', ],
            ["id" => 27, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Autoliquidación plusvalía", "es": "Autoliquidación plusvalía"}', "route" => "/treasury/va-liquidation" ,"pmenus_id" => 25, "order" => 1, "deep" => 2, "type" => "route", "icon" => "", "level" => 1, "group" => "va-liquidation", "group_description" => '{"en": "Value added", "es": "Plusvalias"}', ],
            ["id" => 28, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Treasury", "es": "Tesorería"}', "route" => "" ,"pmenus_id" => 28, "order" => 10, "deep" => 1, "type" => "route", "icon" => "la la-eur", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 29, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Movimientos bancos", "es": "Movimientos bancos"}', "route" => "/treasury/accounts/movements" ,"pmenus_id" => 28, "order" => 10, "deep" => 2, "type" => "route", "icon" => "la la-university", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 31, "created_at" => now(), "updated_at" => now(), "description" => '{"en":"Payment codes","es":"C\u00f3digos de pago"}', "route" => "/treasury/payments/payments-codes" ,"pmenus_id" => 28, "order" => 10, "deep" => 2, "type" => "route", "icon" => "", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 32, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Payments", "es": "Pagos"}', "route" => "" ,"pmenus_id" => 32, "order" => 11, "deep" => 1, "type" => "route", "icon" => "la la-credit-card", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 33, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Make payment", "es": "Realizar pago"}', "route" => "/treasury/payments/pay" ,"pmenus_id" => 32, "order" => 11, "deep" => 2, "type" => "route", "icon" => "", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 34, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Electronic town hall", "es": "Sede electrónica"}', "route" => "" ,"pmenus_id" => 34, "order" => 12, "deep" => 1, "type" => "route", "icon" => "la la-at", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 35, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Access", "es": "Acceso a la sede"}', "route" => "[web-sede]" ,"pmenus_id" => 34, "order" => 12, "deep" => 2, "type" => "url", "icon" => "", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 36, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Nuevo código de pago", "es": "Nuevo código de pago"}', "route" => "/treasury/payments/payment-code" ,"pmenus_id" => 32, "order" => 11, "deep" => 2, "type" => "route", "icon" => "", "level" => 3, "group" => null, "group_description" => null, ],
            ["id" => 37, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Forms", "es": "Impresos y formularios"}', "route" => "" ,"pmenus_id" => 37, "order" => 13, "deep" => 1, "type" => "route", "icon" => "la la-file-text-o", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 38, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "View forms", "es": "Ver impresos y formularios"}', "route" => "/general/forms" ,"pmenus_id" => 24, "order" => 13, "deep" => 2, "type" => "route", "icon" => "la la-file-text-o", "level" => 1, "group" => "general", "group_description" => '{"en": "General", "es": "General"}', ],
            ["id" => 39, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Nueva inscripción", "es": "Nueva inscripción"}', "route" => "/sports/registration" ,"pmenus_id" => 6, "order" => 3, "deep" => 2, "type" => "route", "icon" => "la la-file-medical", "level" => 1, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 40, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Entradas", "es": "Entradas"}', "route" => "" ,"pmenus_id" => 40, "order" => 14, "deep" => 1, "type" => "route", "icon" => "la la-ticket", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 41, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Comprar entradas", "es": "Comprar entradas"}', "route" => "/tickets/buy-tickets" ,"pmenus_id" => 40, "order" => 14, "deep" => 2, "type" => "route", "icon" => "", "level" => 1, "group" => null, "group_description" => null, ],
            ["id" => 42, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Resumen ventas", "es": "Resumen ventas"}', "route" => "/tickets/report" ,"pmenus_id" => 40, "order" => 14, "deep" => 2, "type" => "route", "icon" => "la la-file-text-o", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 44, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Buscar entradas", "es": "Buscar entradas"}', "route" => "/tickets/tickets" ,"pmenus_id" => 40, "order" => 14, "deep" => 2, "type" => "route", "icon" => "la la-search", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 45, "created_at" => now(), "updated_at" => now(), "description" => '{"en":"Payments","es":"Pagos"}', "route" => "/sports/registrations-payments" ,"pmenus_id" => 6, "order" => 4, "deep" => 2, "type" => "route", "icon" => "la la-credit-card", "level" => 2, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 46, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Agendas", "es": "Agendas"}', "route" => "" ,"pmenus_id" => 46, "order" => 15, "deep" => 1, "type" => "route", "icon" => "la la-calendar", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 47, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión de citas", "es": "Gestión de citas"}', "route" => "/general/schedules/appointments" ,"pmenus_id" => 46, "order" => 15, "deep" => 2, "type" => "route", "icon" => "", "level" => 2, "group" => "general", "group_description" => '{"en": "General", "es": "General"}', ],
            ["id" => 48, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Schedules", "es": "Agendas"}', "route" => "/general/schedules/calendar" ,"pmenus_id" => 24, "order" => 15, "deep" => 2, "type" => "route", "icon" => "la la-calendar", "level" => 2, "group" => "general", "group_description" => '{"en": "General", "es": "General"}', ],
            ["id" => 49, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Instalaciones", "es": "Instalaciones"}', "route" => "/sports/installations" ,"pmenus_id" => 6, "order" => 6, "deep" => 2, "type" => "route", "icon" => "la la-microchip", "level" => 2, "group" => "installations", "group_description" => '{"en": "Installations", "es": "Instalaciones"}', ],
            ["id" => 51, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Self-assessment", "es": "Autoliquidaciones"}', "route" => "/treasury/liquidation" ,"pmenus_id" => 25, "order" => 3, "deep" => 2, "type" => "route", "icon" => "", "level" => 1, "group" => "liquidations", "group_description" => '{"en": "Self liquidations", "es": "Autoliquidaciones"}', ],
            ["id" => 52, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión autoliquidaciones", "es": "Gestión autoliquidaciones"}', "route" => "/treasury/liquidations" ,"pmenus_id" => 25, "order" => 4, "deep" => 2, "type" => "route", "icon" => "la la-edit", "level" => 2, "group" => "liquidations", "group_description" => '{"en": "Self liquidations", "es": "Autoliquidaciones"}', ],
            ["id" => 53, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Urbanismo", "es": "Urbanismo"}', "route" => "" ,"pmenus_id" => 53, "order" => 16, "deep" => 1, "type" => "route", "icon" => "la la-building", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 54, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión solares", "es": "Gestión solares"}', "route" => "/town-planning/sandlots" ,"pmenus_id" => 53, "order" => 16, "deep" => 2, "type" => "route", "icon" => "", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 55, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Eventos", "es": "Eventos"}', "route" => "/sports/events" ,"pmenus_id" => 6, "order" => 1, "deep" => 2, "type" => "route", "icon" => "la la-calendar", "level" => 2, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 56, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Groups management", "es": "Gestión grupos"}', "route" => "/general/contacts-groups" ,"pmenus_id" => 24, "order" => 8, "deep" => 2, "type" => "route", "icon" => "la la-users", "level" => 2, "group" => "general", "group_description" => '{"en": "General", "es": "General"}', ],
            ["id" => 57, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión plantillas HTML", "es": "Gestión plantillas HTML"}', "route" => "/admin/html-templates" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-file-code", "level" => 100, "group" => null, "group_description" => null, ],
            ["id" => 58, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Uso instalaciones", "es": "Uso instalaciones"}', "route" => "/sports/reservation" ,"pmenus_id" => 6, "order" => 8, "deep" => 2, "type" => "route", "icon" => "", "level" => 1, "group" => "installations", "group_description" => '{"en": "Installations", "es": "Instalaciones"}', ],
            ["id" => 59, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Reservas", "es": "Reservas"}', "route" => "/sports/reservations" ,"pmenus_id" => 6, "order" => 7, "deep" => 2, "type" => "route", "icon" => "la la-calendar", "level" => 2, "group" => "installations", "group_description" => '{"en": "Installations", "es": "Instalaciones"}', ],
            ["id" => 60, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Town hall data", "es": "Datos ayuntamiento"}', "route" => "/admin/townhall-data" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-university", "level" => 10, "group" => null, "group_description" => null, ],
            ["id" => 61, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Helps setup", "es": "Gestión ayudas"}', "route" => "/admin/helps" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-question", "level" => 100, "group" => null, "group_description" => null, ],
            ["id" => 62, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Conf. autoliquidaciones", "es": "Conf. autoliquidaciones"}', "route" => "/treasury/liquidations-types" ,"pmenus_id" => 25, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-cog", "level" => 3, "group" => "liquidations", "group_description" => '{"en": "Self liquidations", "es": "Autoliquidaciones"}', ],
            ["id" => 63, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión permisos", "es": "Gestión permisos"}', "route" => "/admin/permissions" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-key", "level" => 10, "group" => null, "group_description" => null, ],
            ["id" => 64, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión agendas", "es": "Gestión agendas"}', "route" => "/admin/schedules" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-calendar-check", "level" => 10, "group" => null, "group_description" => null, ],
            ["id" => 65, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión menús", "es": "Gestión menús"}', "route" => "/admin/menus" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-align-justify", "level" => 10, "group" => null, "group_description" => null, ],
            ["id" => 66, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Gestión ayuntamientos", "es": "Gestión ayuntamientos"}', "route" => "/admin/townhalls" ,"pmenus_id" => 14, "order" => 5, "deep" => 2, "type" => "route", "icon" => "la la-university", "level" => 100, "group" => null, "group_description" => null, ],
            ["id" => 67, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Espectáculos", "es": "Espectáculos"}', "route" => "/tickets/shows" ,"pmenus_id" => 40, "order" => 14, "deep" => 2, "type" => "route", "icon" => "las la-theater-masks", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 68, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Notificaciones", "es": "Notificaciones"}', "route" => "/general/notifications" ,"pmenus_id" => 24, "order" => 8, "deep" => 2, "type" => "route", "icon" => "la la-bell", "level" => 1, "group" => "general", "group_description" => '{"en": "General", "es": "General"}', ],
            ["id" => 69, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Rooms", "es": "Salas"}', "route" => "/tickets/rooms" ,"pmenus_id" => 40, "order" => 15, "deep" => 2, "type" => "route", "icon" => "las la-store", "level" => 2, "group" => null, "group_description" => null, ],
            ["id" => 70, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Eventos", "es": "Eventos"}', "route" => "/general/events" ,"pmenus_id" => 24, "order" => 1, "deep" => 2, "type" => "route", "icon" => "la la-calendar", "level" => 2, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 71, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Nueva inscripción", "es": "Nueva inscripción"}', "route" => "/general/registration" ,"pmenus_id" => 24, "order" => 3, "deep" => 2, "type" => "route", "icon" => "la la-file-medical", "level" => 1, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 72, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Inscripciones", "es": "Inscripciones"}', "route" => "/general/registrations" ,"pmenus_id" => 24, "order" => 2, "deep" => 2, "type" => "route", "icon" => "la la-file-alt", "level" => 2, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 73, "created_at" => now(), "updated_at" => now(), "description" => '{"en":"Payments","es":"Pagos"}', "route" => "/general/registrations-payments" ,"pmenus_id" => 24, "order" => 4, "deep" => 2, "type" => "route", "icon" => "la la-credit-card", "level" => 2, "group" => "events", "group_description" => '{"en": "Events", "es": "Eventos"}', ],
            ["id" => 74, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Picaentradas", "es": "Picaentradas"}', "route" => "/general/tickets-chop-select" ,"pmenus_id" => 6, "order" => 9, "deep" => 2, "type" => "route", "icon" => "las la-qrcode", "level" => 2, "group" => "installations", "group_description" => '{"en": "Installations", "es": "Instalaciones"}', ],
            ["id" => 75, "created_at" => now(), "updated_at" => now(), "description" => '{"en": "Picaentradas", "es": "Picaentradas"}', "route" => "/general/tickets-chop-select" ,"pmenus_id" => 40, "order" => 16, "deep" => 2, "type" => "route", "icon" => "las la-qrcode", "level" => 2, "group" => null, "group_description" => null, ],
        ];

        Menu::upsert($records, ['id'], ['description', 'route', 'pmenus_id', 'order', 'deep', 'type', 'group', 'group_description', 'created_at', 'updated_at']);

        Schema::enableForeignKeyConstraints();
    }
}
