<?php

return [
	'mode'                 => 'utf-8',
	'format'               => 'A4',
	'default_font_size'    => '11',
	'default_font'         => 'sans-serif',
	'margin_left'          => 10,
	'margin_right'         => 10,
	'margin_top'           => 35,
	'margin_bottom'        => 20,
	'margin_header'        => 5,
	'margin_footer'        => 5,
	'orientation'          => 'P',
	'title'                => 'Muniges',
	'author'               => '',
	'watermark'            => '',
	'show_watermark'       => false,
	'watermark_font'       => 'sans-serif',
	'display_mode'          => 'fullpage',
	'watermark_text_alpha'  => 0.1,
	'custom_font_dir'       => '',
	'custom_font_data'      => [],
	'auto_language_detection'  => false,
	'temp_dir'              => rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR),
	'pdfa'                  => false,
    'pdfaauto'              => false,
];
